name: ride_sharing_user_app
description: A ride sharing Flutter project.
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  cached_network_image: ^3.2.3
  carousel_slider: ^4.1.1
  connectivity_plus: ^3.0.2
  country_code_picker:
    git:
      url: https://github.com/Alaabadr44/CountryCodePicker.git
      ref: main
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  dotted_border: ^2.0.0+2
  expandable_bottom_sheet: ^1.1.1+1
  file_picker: ^4.6.1
  firebase_core: ^2.3.0
  firebase_messaging: ^14.1.3
  flutter:
    sdk: flutter
  flutter_animarker: ^3.2.0
  flutter_downloader: ^1.8.3
  flutter_html: ^3.0.0-alpha.5
  flutter_local_notifications: ^12.0.4
  flutter_polyline_points: ^2.0.0
  flutter_secure_storage: any
  flutter_svg: ^1.1.6
  flutter_widget_from_html_core: ^0.8.5+1
  geocoder2: null
  geolocator: ^9.0.1
  get: ^4.6.5
  get_it: ^7.6.4
  google_maps_flutter: ^2.2.3
  image_picker: ^0.8.6
  intl: ^0.17.0
  loading_overlay_pro: ^2.1.1
  modal_bottom_sheet: ^2.1.2
  open_file_safe: ^3.2.3
  path_provider: ^2.0.11
  percent_indicator: ^4.0.1
  permission_handler: ^10.2.0
  pin_code_fields: ^7.4.0
  pretty_dio_logger: ^1.3.1
  shared_preferences: 
  shimmer: ^3.0.0
  syncfusion_flutter_datepicker: ^22.2.12
  url_launcher: ^6.1.14
  geocoding:
  flutter_spinkit:
#  map_location_picker:

dependency_overrides:
  modal_bottom_sheet:
    git:
      url: https://github.com/danReynolds/modal_bottom_sheet.git
      path: modal_bottom_sheet

  http: null
  intl: null

dev_dependencies:
  build_runner: null
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  retrofit_generator: null

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/
    - assets/svg/

  fonts:
    - family: SFProText
      fonts:
        - asset: assets/font/sf-pro-text-light.ttf
          weight: 300
        - asset: assets/font/sf-pro-text-regular.ttf
          weight: 400
        - asset: assets/font/sf-pro-text-medium.ttf
          weight: 500
        - asset: assets/font/sf-pro-text-semibold.ttf
          weight: 600
        - asset: assets/font/sf-pro-text-bold.ttf
          weight: 700
        - asset: assets/font/sf-pro-text-heavy.ttf
          weight: 900
