name: ride_sharing_user_app
description: A ride sharing Flutter project.
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  another_stepper: ^1.2.2
  ansicolor: null
  barbecue: null
  cached_network_image: ^3.2.3
  carousel_slider: ^4.1.1
  chucker_flutter: ^1.6.1
  connectivity_plus: ^2.3.4
  country_code_picker:
    git:
      url: https://github.com/Alaabadr44/CountryCodePicker.git
      ref: main
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  dotted_border: ^2.0.0+2
  equatable: ^2.0.5
  expandable_bottom_sheet: ^1.1.1+1
  file_picker: null
  firebase_core: ^2.3.0
  firebase_messaging: ^14.1.3
  fl_chart: null
  flutter:
    sdk: flutter
  flutter_animarker: ^3.2.0
  flutter_dotenv: ^5.1.0
  flutter_downloader: ^1.8.3
  flutter_html: ^3.0.0-alpha.5
  flutter_local_notifications: ^12.0.4
  flutter_polyline_points: ^2.0.0
  flutter_screenutil: null
  flutter_secure_storage: any
  flutter_spinkit: null
  flutter_staggered_animations: null
  flutter_svg: null
  flutter_widget_from_html_core: ^0.8.5+1
  geocoder2: null
  geocoding: null
  geolocator: ^9.0.1
  get: ^4.6.5
  get_it: ^7.6.4
  google_maps_flutter: null
  image_picker: ^0.8.6
  intl: ^0.17.0
  jiffy: null
  loading_overlay_pro: ^2.1.1
  lottie: null
  moyasar: ^2.0.2
  package_info_plus: ^4.2.0
  path_provider: ^2.0.11
  percent_indicator: ^4.0.1
  permission_handler: ^10.2.0
  pin_code_fields: ^7.4.0
  pretty_dio_logger: ^1.3.1
  pull_to_refresh: ^2.0.0
  restart_app: ^1.2.1
  share_plus: null
  shared_preferences: null
  shimmer: ^3.0.0
  socket_io_client: ^2.0.3+1
  sqflite: ^2.3.0
  syncfusion_flutter_datepicker: ^22.2.12
  top_snackbar_flutter: null
  url_launcher: ^6.1.14

dependency_overrides:
  #  modal_bottom_sheet:
  #    git:
  #      url: https://github.com/danReynolds/modal_bottom_sheet.git
  #      path: modal_bottom_sheet
  # dio: ^4.0.4
  ? http
  ? intl

dev_dependencies:
  build_runner: null
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  retrofit_generator: null

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/
    - assets/svg/
    - assets/lottie/
    - .env
  fonts:
    - family: SFProText
      fonts:
        - asset: assets/font/sf-pro-text-light.ttf
          weight: 300
        - asset: assets/font/sf-pro-text-regular.ttf
          weight: 400
        - asset: assets/font/sf-pro-text-medium.ttf
          weight: 500
        - asset: assets/font/sf-pro-text-semibold.ttf
          weight: 600
        - asset: assets/font/sf-pro-text-bold.ttf
          weight: 700
        - asset: assets/font/sf-pro-text-heavy.ttf
          weight: 900
